name: Sentry Publish
on: [deployment]
jobs:
  publish-sentry:
    if: github.deployment.environment == 'Production'
    environment: Production
    steps:
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        version: mbtaParkingMap@${{ github.sha }}